apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-replicas
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: apache-replicaset
          image: deeptiwa/myhttpd
  replicas: 3
  selector:
    matchLabels:
      type: front-end

