apiVersion: v1
kind: ReplicationController
metadata:
   name: myapp-rc
   labels:
      app: myapp
      type: front-end
spec:
    template:
        metadata:
            name: myapp-prod
            labels:
              app: myapp
        spec:
            containers:
              - name: myapp-nginx
                image: nginx
    replicas: 2
